ALTER TABLE `sys_org` ADD COLUMN `WEBSITE` varchar(256) AFTER `SN`, 
ADD COLUMN `TELEPHONE` varchar(20) AFTER `WEBSITE`;

ALTER TABLE `sys_user` 
ADD COLUMN `FIRST_SPELL` varchar(20) AFTER `PICTURE`, 
ADD COLUMN `EMP_ID` varchar(20) AFTER `FIRST_SPELL`, 
ADD COLUMN `DES` varchar(255) AFTER `EMP_ID`;


ALTER TABLE `sys_res` 
ADD COLUMN `PARAM` varchar(256) COMMENT '附加参数，多个参数逗号(;)分割' AFTER `ALIAS`;


ALTER TABLE `bpm_definition` 
ADD COLUMN `BUSSINESSTYPE` varchar(256) AFTER `TYPEID`;