ALTER TABLE `sys_org` 
ADD COLUMN `WEBSITE` varchar(256) COMMENT '网站地址' AFTER `SN`, 
ADD COLUMN `TELEPHONE` varchar(20) COMMENT '联系电话' AFTER `WEBSITE`;

ALTER TABLE `sys_user` 
ADD COLUMN `FIRST_SPELL` varchar(20) COMMENT '姓名拼音字母' AFTER `PICTURE`, 
ADD COLUMN `EMP_ID` varchar(20) COMMENT '员工编号' AFTER `FIRST_SPELL`, 
ADD COLUMN `DES` varchar(255) COMMENT '详细描述' AFTER `EMP_ID`;


ALTER TABLE `sys_res` 
ADD COLUMN `PARAM` varchar(256) COMMENT '附加参数，多个参数逗号(;)分割' AFTER `ALIAS`;


ALTER TABLE `bpm_definition` 
ADD COLUMN `BUSINESSTYPE` varchar(256) COMMENT '业务类型' AFTER `TYPEID`;

ALTER TABLE `bpm_form_table` 
ADD COLUMN `BUSINESSTYPE` varchar(20) COMMENT '业务类型' AFTER `ISMAIN`;

ALTER TABLE `bpm_form_def` 
ADD COLUMN `templateId` bigint(20) COMMENT '模板编号' AFTER `HTML`;